// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d3febc91-b2eb-4d92-9909-fab1f3ba86ec";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMotorDirectionChange();
void onMotorSpeedChange();
void onMotorSwitchChange();

float humidity;
float temperature;
int motor_direction;
int motor_speed;
bool motor_switch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(motor_direction, READWRITE, ON_CHANGE, onMotorDirectionChange);
  ArduinoCloud.addProperty(motor_speed, READWRITE, ON_CHANGE, onMotorSpeedChange);
  ArduinoCloud.addProperty(motor_switch, READWRITE, ON_CHANGE, onMotorSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
